# Generated by Django 3.2.4 on 2021-08-03 06:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_address', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=255)),
                ('subject', models.CharField(max_length=78)),
                ('body', models.CharField(max_length=40000)),
                ('send_on', models.DateTimeField(default=datetime.datetime(2021, 8, 3, 6, 53, 20, 934477, tzinfo=utc))),
                ('attachment_file', models.FileField(upload_to='')),
                ('recipients_list', models.ManyToManyField(related_name='mail_list', to='api.MailRecipient')),
            ],
        ),
    ]
