# Generated by Django 3.2.5 on 2021-09-02 15:13

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=255)),
                ('subject', models.CharField(max_length=78)),
                ('body', models.CharField(max_length=40000)),
                ('send_on', models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 2, 20, 43, 17, 947253))),
                ('recipients_list', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=255), size=None)),
                ('attachment_file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
