# Generated by Django 3.2.5 on 2021-08-21 07:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmail',
            name='send_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 21, 7, 39, 29, 918395, tzinfo=utc)),
        ),
    ]
