# Generated by Django 3.2.5 on 2021-08-21 07:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_scheduledmail_send_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmail',
            name='send_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 21, 7, 41, 35, 283565, tzinfo=utc)),
        ),
    ]
