# Generated by Django 3.2.5 on 2021-08-21 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_scheduledmail_send_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmail',
            name='send_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 21, 13, 17, 4, 894418)),
        ),
    ]
