# Generated by Django 3.2.4 on 2021-08-03 07:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210803_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='scheduledmail',
            name='send_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 7, 48, 20, 132103, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='scheduledmail',
            name='recipients_list',
            field=models.ManyToManyField(related_name='mail_list', to='api.MailRecipient'),
        ),
    ]
