# Generated by Django 3.2.4 on 2021-08-03 07:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210803_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmail',
            name='send_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 7, 58, 11, 602469, tzinfo=utc)),
        ),
    ]
